# Generated by Django 2.1.5 on 2020-04-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20200405_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
